import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

import Navbar from "@/components/layout/Navbar";
import Sidebar from "@/components/layout/Sidebar";
import Footer from "@/components/layout/Footer";
import ReadingProgress from "@/components/ReadingProgress";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex mx-auto flex-col">
        <Providers>
          <ReadingProgress />
          <Navbar />
          <div className="max-w-7x1 lg:ml-auto lg:mr-auto mx-0 flex">

            <main className="flex-1 min-h-screen p-6">
              {children}
            </main>

          </div>
          <Footer />
        </Providers>
        </body>
    </html>
  );
}
